import {
  Briefcase,
  Code,
  DollarSign,
  Gift,
  Upload,
  Users,
  TrendingUp,
  Building2,
  Landmark,
  Laptop,
  Megaphone,
  Truck,
  HeartPulse,
  Calculator,
  LineChart,
  PiggyBank,
  Store,
  ShoppingCart,
  BarChart3,
  Presentation,
  UserCheck,
  UserCog,
  Handshake,
  Package,
  Factory,
  Warehouse,
  ClipboardList,
  Stethoscope,
  Pill,
  Activity,
  Wrench,
  Hammer,
  Lightbulb,
  Monitor,
  Smartphone,
  Globe,
  Cloud,
  Database,
  Shield,
  Lock,
  Cog,
  Settings,
  Pencil,
  PenTool,
  Camera,
  Video,
  Music,
  Mic,
  FileText,
  Book,
  BookOpen,
  Award,
  Star,
  Heart,
  Home,
  MapPin,
  Phone,
  Mail,
  MessageSquare,
  Send,
  Share2,
  Link,
  Zap,
  Rocket,
  Plane,
  Car,
  Ship,
  Coffee,
  Utensils,
  Bed,
  Building,
  Hotel,
  Banknote,
  CreditCard,
  Percent,
  Receipt,
  Scale,
  Gavel,
  Layers,
  Grid,
  Layout,
  LayoutDashboard,
  PieChart,
  Network,
  GitBranch,
  Terminal,
  Binary,
  Cpu,
  HardDrive,
  Server,
  Wifi,
  Eye,
  Brain,
  Microscope,
  TestTube,
  Beaker,
  Atom,
  Leaf,
  Sun,
  Flame,
  GraduationCap,
  Target,
  Bot,
  Palette,
  Search,
  Headphones,
  type LucideIcon,
} from "lucide-react";

/**
 * GroUp Academy: Institutional Icon Registry
 * CTO Reference: Authoritative mapping of database strings to Lucide components.
 * Logic: Implements aliased resiliency and semantic sector clustering.
 */

export const iconMap: Record<string, LucideIcon> = {
  // --- HUD: Business & Finance ---
  briefcase: Briefcase,
  landmark: Landmark,
  banknote: Banknote,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  "piggy-bank": PiggyBank,
  calculator: Calculator,
  receipt: Receipt,
  percent: Percent,
  "trending-up": TrendingUp,
  "line-chart": LineChart,
  "bar-chart-3": BarChart3,
  "pie-chart": PieChart,
  presentation: Presentation,

  // --- HUD: Sales & Marketing ---
  megaphone: Megaphone,
  store: Store,
  "shopping-cart": ShoppingCart,
  handshake: Handshake,

  // --- HUD: Operations & Logistics ---
  truck: Truck,
  package: Package,
  factory: Factory,
  warehouse: Warehouse,
  "clipboard-list": ClipboardList,

  // --- HUD: Healthcare & Pharma ---
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  activity: Activity,
  heart: Heart,

  // --- HUD: Technology ---
  code: Code,
  laptop: Laptop,
  monitor: Monitor,
  smartphone: Smartphone,
  globe: Globe,
  cloud: Cloud,
  database: Database,
  server: Server,
  terminal: Terminal,
  binary: Binary,
  cpu: Cpu,
  "hard-drive": HardDrive,
  network: Network,
  "git-branch": GitBranch,
  wifi: Wifi,

  // --- HUD: HR & People ---
  users: Users,
  "user-check": UserCheck,
  "user-cog": UserCog,

  // --- HUD: Creative & Design ---
  palette: Palette,
  pencil: Pencil,
  "pen-tool": PenTool,
  camera: Camera,
  video: Video,
  music: Music,
  mic: Mic,

  // --- HUD: Education & Learning ---
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  book: Book,
  "file-text": FileText,
  award: Award,

  // --- HUD: Infrastructure ---
  "building-2": Building2,
  building2: Building2,
  building: Building,
  hotel: Hotel,
  home: Home,
  "map-pin": MapPin,

  // --- HUD: Transportation ---
  plane: Plane,
  car: Car,
  ship: Ship,

  // --- HUD: Security & Science ---
  shield: Shield,
  lock: Lock,
  scale: Scale,
  gavel: Gavel,
  microscope: Microscope,
  "test-tube": TestTube,
  beaker: Beaker,
  atom: Atom,
  brain: Brain,

  // --- HUD: Miscellaneous ---
  star: Star,
  target: Target,
  lightbulb: Lightbulb,
  zap: Zap,
  rocket: Rocket,
  bot: Bot,
  gift: Gift,
  upload: Upload,
  search: Search,
  headphones: Headphones,
};

export const defaultIcon = Briefcase;

/**
 * HUD: Safe Icon Resolver
 * Returns the mapped icon or the institutional default.
 */
export function getIcon(iconName: string | null | undefined): LucideIcon {
  if (!iconName) return defaultIcon;
  return iconMap[iconName] || defaultIcon;
}
